import { Observable, of } from 'rxjs';
import { Injectable } from '@angular/core';
import { Director } from '../model/director';

@Injectable({
  providedIn: 'root',
})
export class DirectorService {
  list: Director[] = [
    {
      _id: 1,
      fullName: 'Justino Haselwood',
      nationality: 'HN',
      dateOfBirth: '2021-06-19',
      mostFamousMovie: 'Goldengirl',
    },
    {
      _id: 2,
      fullName: 'Humbert Foad',
      nationality: 'RU',
      dateOfBirth: '2021-10-14',
      mostFamousMovie: 'Good Son, The',
    },
    {
      _id: 3,
      fullName: 'Maureene Rominov',
      nationality: 'NI',
      dateOfBirth: '2021-09-01',
      mostFamousMovie: 'Destiny (a.k.a. Between Two Worlds) (Der müde Tod)',
    },
    {
      _id: 4,
      fullName: 'Amalle Parlet',
      nationality: 'VE',
      dateOfBirth: '2021-10-20',
      mostFamousMovie: 'Welcome to Sarajevo',
    },
    {
      _id: 5,
      fullName: 'Hallie Arnaldy',
      nationality: 'JP',
      dateOfBirth: '2021-10-21',
      mostFamousMovie: 'Jesse Stone: No Remorse',
    },
    {
      _id: 6,
      fullName: 'Perkin Pendred',
      nationality: 'BR',
      dateOfBirth: '2021-08-26',
      mostFamousMovie:
        'Investigation of a Citizen Above Suspicion (Indagine su un cittadino al di sopra di ogni sospetto)',
    },
    {
      _id: 7,
      fullName: 'Bellanca Ahmed',
      nationality: 'CN',
      dateOfBirth: '2021-10-09',
      mostFamousMovie: 'Caliber 9',
    },
    {
      _id: 8,
      fullName: 'Anica Pappi',
      nationality: 'ID',
      dateOfBirth: '2021-12-13',
      mostFamousMovie: 'Madame Bovary',
    },
    {
      _id: 9,
      fullName: 'Vittoria Toop',
      nationality: 'ID',
      dateOfBirth: '2021-10-11',
      mostFamousMovie: 'Firm, The',
    },
    {
      _id: 10,
      fullName: 'Devonne Heakey',
      nationality: 'PT',
      dateOfBirth: '2022-04-12',
      mostFamousMovie: 'GhostWatcher',
    },
    {
      _id: 11,
      fullName: 'Elaina Vignaux',
      nationality: 'PH',
      dateOfBirth: '2022-03-24',
      mostFamousMovie: 'Groove',
    },
    {
      _id: 12,
      fullName: 'Justine Rabidge',
      nationality: 'PH',
      dateOfBirth: '2021-07-27',
      mostFamousMovie: 'Diamond Arm, The (Brilliantovaya ruka)',
    },
    {
      _id: 13,
      fullName: 'Jackson Zanni',
      nationality: 'GR',
      dateOfBirth: '2021-07-06',
      mostFamousMovie: 'In the Basement',
    },
    {
      _id: 14,
      fullName: 'Dixie Jiru',
      nationality: 'PT',
      dateOfBirth: '2022-01-25',
      mostFamousMovie: 'Running',
    },
    {
      _id: 15,
      fullName: 'Lark Vahl',
      nationality: 'CN',
      dateOfBirth: '2021-08-10',
      mostFamousMovie: 'The Beaver Trilogy',
    },
    {
      _id: 16,
      fullName: 'Malinde Capoun',
      nationality: 'CZ',
      dateOfBirth: '2021-11-03',
      mostFamousMovie: 'American Friends',
    },
    {
      _id: 17,
      fullName: 'Aluin Boig',
      nationality: 'SE',
      dateOfBirth: '2021-09-10',
      mostFamousMovie: 'Country Girl, The',
    },
    {
      _id: 18,
      fullName: 'Roxanne Walkey',
      nationality: 'CN',
      dateOfBirth: '2021-07-05',
      mostFamousMovie: 'Tape',
    },
    {
      _id: 19,
      fullName: 'Corissa Vannoni',
      nationality: 'CN',
      dateOfBirth: '2021-10-23',
      mostFamousMovie: 'The Rise',
    },
    {
      _id: 20,
      fullName: 'Ogdan Shilvock',
      nationality: 'PH',
      dateOfBirth: '2022-01-26',
      mostFamousMovie: 'Pretty Sweet',
    },
    {
      _id: 21,
      fullName: 'Ingrim Boik',
      nationality: 'UG',
      dateOfBirth: '2022-01-24',
      mostFamousMovie: 'Battles Without Honor & Humanity (Jingi naki tatakai)',
    },
    {
      _id: 22,
      fullName: 'Faina Kasparski',
      nationality: 'CN',
      dateOfBirth: '2021-12-24',
      mostFamousMovie: 'Baby Boy',
    },
    {
      _id: 23,
      fullName: 'Alison McGurgan',
      nationality: 'RU',
      dateOfBirth: '2021-10-07',
      mostFamousMovie: 'Silent Night, Deadly Night 5: The Toy Maker',
    },
    {
      _id: 24,
      fullName: 'Norman Grioli',
      nationality: 'CN',
      dateOfBirth: '2021-08-16',
      mostFamousMovie: 'Dog Nail Clipper (Koirankynnenleikkaaja)',
    },
    {
      _id: 25,
      fullName: 'Noell Kaspar',
      nationality: 'KZ',
      dateOfBirth: '2022-02-14',
      mostFamousMovie: 'Home of the Brave',
    },
    {
      _id: 26,
      fullName: 'Jeremiah Faires',
      nationality: 'ID',
      dateOfBirth: '2022-01-13',
      mostFamousMovie: 'The Casino Murder Case',
    },
    {
      _id: 27,
      fullName: 'Greg Brann',
      nationality: 'CN',
      dateOfBirth: '2022-01-22',
      mostFamousMovie: 'Window to Paris (Okno v Parizh)',
    },
    {
      _id: 28,
      fullName: 'Baldwin Ratter',
      nationality: 'CN',
      dateOfBirth: '2022-03-31',
      mostFamousMovie: 'Prodigal, The',
    },
    {
      _id: 29,
      fullName: 'Petunia Tarbath',
      nationality: 'CN',
      dateOfBirth: '2021-12-18',
      mostFamousMovie: 'Fox, The',
    },
    {
      _id: 30,
      fullName: 'Lesley Bello',
      nationality: 'PE',
      dateOfBirth: '2021-07-29',
      mostFamousMovie: 'Deux mondes, Les',
    },
    {
      _id: 31,
      fullName: 'Verina Giacaponi',
      nationality: 'CN',
      dateOfBirth: '2021-10-15',
      mostFamousMovie: 'Silver Stallion (Silver Brumpy, The)',
    },
    {
      _id: 32,
      fullName: 'Milty Tuny',
      nationality: 'GT',
      dateOfBirth: '2021-06-20',
      mostFamousMovie: 'Max Dugan Returns',
    },
    {
      _id: 33,
      fullName: 'Lilla Jodlkowski',
      nationality: 'HU',
      dateOfBirth: '2021-10-12',
      mostFamousMovie: 'Lucky Numbers',
    },
    {
      _id: 34,
      fullName: 'Inna Tosney',
      nationality: 'CO',
      dateOfBirth: '2022-01-02',
      mostFamousMovie: 'Mr. Smith Goes to Washington',
    },
    {
      _id: 35,
      fullName: 'Melli Rawstron',
      nationality: 'JP',
      dateOfBirth: '2021-12-11',
      mostFamousMovie: 'Cruel Intentions',
    },
    {
      _id: 36,
      fullName: 'Cosetta Jephcote',
      nationality: 'RU',
      dateOfBirth: '2021-08-12',
      mostFamousMovie: 'Chilly Scenes of Winter (Head Over Heels)',
    },
    {
      _id: 37,
      fullName: 'Bronson Spilsbury',
      nationality: 'CN',
      dateOfBirth: '2022-03-02',
      mostFamousMovie: 'Koti-ikävä',
    },
    {
      _id: 38,
      fullName: 'Hoyt Neesham',
      nationality: 'CN',
      dateOfBirth: '2021-09-23',
      mostFamousMovie: 'Water Horse: Legend of the Deep, The',
    },
    {
      _id: 39,
      fullName: 'Deni Rosenhaus',
      nationality: 'ID',
      dateOfBirth: '2022-01-12',
      mostFamousMovie: 'Crime Spree',
    },
    {
      _id: 40,
      fullName: 'Kitti MacRedmond',
      nationality: 'ID',
      dateOfBirth: '2021-12-25',
      mostFamousMovie: 'Battle: Los Angeles',
    },
    {
      _id: 41,
      fullName: 'Dorothea Tuddenham',
      nationality: 'SE',
      dateOfBirth: '2022-05-14',
      mostFamousMovie: 'Intruders',
    },
    {
      _id: 42,
      fullName: 'Alfons Morcomb',
      nationality: 'SE',
      dateOfBirth: '2022-05-08',
      mostFamousMovie: 'Bride Came C.O.D., The',
    },
    {
      _id: 43,
      fullName: 'Ardisj Dinsdale',
      nationality: 'SI',
      dateOfBirth: '2021-11-01',
      mostFamousMovie: 'Moving Midway',
    },
    {
      _id: 44,
      fullName: 'Sigfried Guare',
      nationality: 'SE',
      dateOfBirth: '2021-12-24',
      mostFamousMovie: 'The Four Feathers',
    },
    {
      _id: 45,
      fullName: 'Denice Giacomozzo',
      nationality: 'FR',
      dateOfBirth: '2021-08-24',
      mostFamousMovie: 'Beastie Boys: Sabotage',
    },
    {
      _id: 46,
      fullName: 'Kelsey Lukash',
      nationality: 'ID',
      dateOfBirth: '2022-02-21',
      mostFamousMovie: 'Topaze',
    },
    {
      _id: 47,
      fullName: 'Ami Pally',
      nationality: 'GR',
      dateOfBirth: '2021-07-16',
      mostFamousMovie: 'Gospa',
    },
    {
      _id: 48,
      fullName: 'Onida Hylton',
      nationality: 'BI',
      dateOfBirth: '2021-07-09',
      mostFamousMovie: 'Hitler: The Rise of Evil',
    },
    {
      _id: 49,
      fullName: 'Beaufort Saladin',
      nationality: 'IT',
      dateOfBirth: '2021-11-13',
      mostFamousMovie: 'Invention of Lying, The',
    },
    {
      _id: 50,
      fullName: 'Pippo Ziemke',
      nationality: 'JP',
      dateOfBirth: '2022-02-07',
      mostFamousMovie: 'Northwest Passage',
    },
    {
      _id: 51,
      fullName: 'Lee Glede',
      nationality: 'CN',
      dateOfBirth: '2021-06-01',
      mostFamousMovie: 'Paper Will Be Blue, The (Hîrtia va fi albastrã)',
    },
    {
      _id: 52,
      fullName: 'Ruperta Matyukon',
      nationality: 'CO',
      dateOfBirth: '2021-11-02',
      mostFamousMovie: 'Saving Silverman (Evil Woman)',
    },
    {
      _id: 53,
      fullName: 'Lilla Hilhouse',
      nationality: 'BR',
      dateOfBirth: '2021-11-05',
      mostFamousMovie: 'Kid & I, The',
    },
    {
      _id: 54,
      fullName: 'Bernard Sherrum',
      nationality: 'CN',
      dateOfBirth: '2022-04-14',
      mostFamousMovie: 'Intohimon vallassa',
    },
    {
      _id: 55,
      fullName: 'Beryl Fernie',
      nationality: 'CN',
      dateOfBirth: '2022-04-05',
      mostFamousMovie: 'The Brain',
    },
    {
      _id: 56,
      fullName: 'Hastie Feldmark',
      nationality: 'NG',
      dateOfBirth: '2022-05-11',
      mostFamousMovie: 'Poll Diaries, The (Poll)',
    },
    {
      _id: 57,
      fullName: 'Charissa Ateridge',
      nationality: 'BR',
      dateOfBirth: '2022-04-29',
      mostFamousMovie: 'King Lear',
    },
    {
      _id: 58,
      fullName: 'Dew Blow',
      nationality: 'GR',
      dateOfBirth: '2021-11-27',
      mostFamousMovie: 'Polar Express, The',
    },
    {
      _id: 59,
      fullName: 'Daron Mansell',
      nationality: 'ID',
      dateOfBirth: '2021-08-23',
      mostFamousMovie: 'Killers, The',
    },
    {
      _id: 60,
      fullName: 'Guillaume Giacomo',
      nationality: 'FM',
      dateOfBirth: '2021-11-14',
      mostFamousMovie: 'Court Jester, The',
    },
    {
      _id: 61,
      fullName: 'Stella Stean',
      nationality: 'CN',
      dateOfBirth: '2022-01-22',
      mostFamousMovie: 'The Cheat',
    },
    {
      _id: 62,
      fullName: 'Alyss Hallihane',
      nationality: 'UZ',
      dateOfBirth: '2021-12-20',
      mostFamousMovie: 'Sympathy for the Devil',
    },
    {
      _id: 63,
      fullName: 'Daloris Soares',
      nationality: 'BR',
      dateOfBirth: '2021-12-04',
      mostFamousMovie: 'Any Number Can Win (Mélodie en sous-sol )',
    },
    {
      _id: 64,
      fullName: 'Gavin Brome',
      nationality: 'OM',
      dateOfBirth: '2021-10-19',
      mostFamousMovie: 'Training Day',
    },
    {
      _id: 65,
      fullName: 'Kennett Buten',
      nationality: 'RU',
      dateOfBirth: '2022-02-16',
      mostFamousMovie: 'Against The Sun',
    },
    {
      _id: 66,
      fullName: 'Miller Gotch',
      nationality: 'BR',
      dateOfBirth: '2022-02-06',
      mostFamousMovie: "Recess: School's Out",
    },
    {
      _id: 67,
      fullName: 'Joann Englishby',
      nationality: 'FR',
      dateOfBirth: '2022-05-17',
      mostFamousMovie: 'Cry Freedom',
    },
    {
      _id: 68,
      fullName: 'Ermentrude Dedney',
      nationality: 'CN',
      dateOfBirth: '2022-02-10',
      mostFamousMovie: 'Under the Flag of the Rising Sun',
    },
    {
      _id: 69,
      fullName: 'Krystalle Dodamead',
      nationality: 'ID',
      dateOfBirth: '2021-08-06',
      mostFamousMovie: 'Sixth of the World, A (Shestaya chast mira)',
    },
    {
      _id: 70,
      fullName: 'Montgomery Breheny',
      nationality: 'CO',
      dateOfBirth: '2022-04-17',
      mostFamousMovie: 'Shaggy Dog, The',
    },
    {
      _id: 71,
      fullName: 'Cesya Alen',
      nationality: 'BR',
      dateOfBirth: '2021-08-04',
      mostFamousMovie: 'Contracted',
    },
    {
      _id: 72,
      fullName: 'Stacee Grelik',
      nationality: 'CN',
      dateOfBirth: '2021-12-05',
      mostFamousMovie: 'Salvation Boulevard',
    },
    {
      _id: 73,
      fullName: 'Alley Doel',
      nationality: 'CN',
      dateOfBirth: '2021-06-14',
      mostFamousMovie: 'Valentino: The Last Emperor',
    },
    {
      _id: 74,
      fullName: 'Randee Rowden',
      nationality: 'CN',
      dateOfBirth: '2022-03-16',
      mostFamousMovie: 'Task, The',
    },
    {
      _id: 75,
      fullName: 'Marlo Treleven',
      nationality: 'PH',
      dateOfBirth: '2021-08-21',
      mostFamousMovie: 'Yes, But... (Oui, mais...)',
    },
    {
      _id: 76,
      fullName: 'Margery Orpwood',
      nationality: 'CN',
      dateOfBirth: '2021-11-17',
      mostFamousMovie: 'Wings (Krylya)',
    },
    {
      _id: 77,
      fullName: 'Shalom Dorricott',
      nationality: 'PL',
      dateOfBirth: '2022-03-09',
      mostFamousMovie: 'Bride of the Wind',
    },
    {
      _id: 78,
      fullName: 'Sheridan Speight',
      nationality: 'US',
      dateOfBirth: '2021-08-17',
      mostFamousMovie: 'Road North (Tie pohjoiseen)',
    },
    {
      _id: 79,
      fullName: 'Theodosia Timblett',
      nationality: 'ID',
      dateOfBirth: '2022-05-16',
      mostFamousMovie:
        'Children of Noisy Village, The (a.k.a Children of Bullerby Village, The) (Alla vi barn i Bullerbyn)',
    },
    {
      _id: 80,
      fullName: 'Elly Strotone',
      nationality: 'HR',
      dateOfBirth: '2021-10-03',
      mostFamousMovie: 'The Walking Hills',
    },
    {
      _id: 81,
      fullName: 'Fancie Molloy',
      nationality: 'US',
      dateOfBirth: '2021-09-20',
      mostFamousMovie: 'Tuesdays with Morrie',
    },
    {
      _id: 82,
      fullName: 'Fanya Chicotti',
      nationality: 'ID',
      dateOfBirth: '2021-10-01',
      mostFamousMovie:
        'Eccentricities of a Blonde-haired Girl (Singularidades de uma Rapariga Loura)',
    },
    {
      _id: 83,
      fullName: 'Che Peacher',
      nationality: 'CN',
      dateOfBirth: '2021-07-20',
      mostFamousMovie: 'On the Riviera',
    },
    {
      _id: 84,
      fullName: 'Carlos Barsam',
      nationality: 'CO',
      dateOfBirth: '2021-10-28',
      mostFamousMovie: 'Wipers Times, The',
    },
    {
      _id: 85,
      fullName: 'Izak Senecaut',
      nationality: 'JP',
      dateOfBirth: '2022-04-18',
      mostFamousMovie: 'Ask Me Anything',
    },
    {
      _id: 86,
      fullName: 'Shay Embery',
      nationality: 'CN',
      dateOfBirth: '2021-06-28',
      mostFamousMovie: 'Seoul Searching',
    },
    {
      _id: 87,
      fullName: 'Merwin Grandham',
      nationality: 'ID',
      dateOfBirth: '2022-04-03',
      mostFamousMovie: 'Common',
    },
    {
      _id: 88,
      fullName: 'Roderigo Denisovo',
      nationality: 'GE',
      dateOfBirth: '2021-05-31',
      mostFamousMovie: 'Deadfall',
    },
    {
      _id: 89,
      fullName: 'Giraud Bowen',
      nationality: 'TH',
      dateOfBirth: '2021-07-16',
      mostFamousMovie: 'Muck',
    },
    {
      _id: 90,
      fullName: 'Barny Conroy',
      nationality: 'ID',
      dateOfBirth: '2021-10-19',
      mostFamousMovie: 'Calling Dr. Death',
    },
    {
      _id: 91,
      fullName: 'Betsy Tittletross',
      nationality: 'FR',
      dateOfBirth: '2021-11-18',
      mostFamousMovie: 'Message in a Bottle',
    },
    {
      _id: 92,
      fullName: 'Mariya Pantecost',
      nationality: 'UA',
      dateOfBirth: '2022-02-28',
      mostFamousMovie: 'Secuestro Express',
    },
    {
      _id: 93,
      fullName: 'Ethan Westmarland',
      nationality: 'AM',
      dateOfBirth: '2021-12-11',
      mostFamousMovie: 'Once Upon a Time in America',
    },
    {
      _id: 94,
      fullName: 'Debi Osmon',
      nationality: 'AR',
      dateOfBirth: '2021-10-14',
      mostFamousMovie: 'Demon Lover Diary',
    },
    {
      _id: 95,
      fullName: 'Loutitia Cuseick',
      nationality: 'CN',
      dateOfBirth: '2021-08-03',
      mostFamousMovie: 'The Vixen',
    },
    {
      _id: 96,
      fullName: 'Constancy Kelshaw',
      nationality: 'ET',
      dateOfBirth: '2022-03-28',
      mostFamousMovie: 'Trials of Muhammad Ali, The',
    },
    {
      _id: 97,
      fullName: 'Ekaterina Curee',
      nationality: 'PL',
      dateOfBirth: '2022-05-07',
      mostFamousMovie: 'Buddies (Colegas)',
    },
    {
      _id: 98,
      fullName: 'Wells Melburg',
      nationality: 'CN',
      dateOfBirth: '2021-09-05',
      mostFamousMovie: 'Summer Place, A',
    },
    {
      _id: 99,
      fullName: 'Hansiain Sacco',
      nationality: 'CN',
      dateOfBirth: '2021-09-18',
      mostFamousMovie: "French Minister, The (Quai d'Orsay)",
    },
    {
      _id: 100,
      fullName: 'Cozmo Vila',
      nationality: 'ID',
      dateOfBirth: '2021-09-13',
      mostFamousMovie: 'Hangar 18',
    },
  ];

  constructor() {}

  getAll(): Observable<Director[]> {
    return of(this.list);
  }
}
