import { WatchedMovie } from './../model/watched-movie';
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class WatchedMovieService {
  list: WatchedMovie[] = [
    {
      _id: 1,
      foreignTitle: 'The Shawshank Redemption',
      hungarianTitle: 'A remény rabjai',
      director: 'Frank Darabont',
      releaseYear: 1994,
      length: 142,
      genre: 'drama',
      imdbRank: '1',
      imdbAverage: 9.3,
      imdbID: 'tt0111161',
      mainActor1: 'Tim Robbins',
      mainActor2: 'Morgan Freeman',
    },
    {
      _id: 2,
      foreignTitle: 'The Godfather',
      hungarianTitle: 'A keresztapa',
      director: 'Francis Ford Coppola',
      releaseYear: 1972,
      length: 175,
      genre: 'crime, drama',
      imdbRank: '2',
      imdbAverage: 9.2,
      imdbID: 'tt0068646',
      mainActor1: 'Marlond Brando',
      mainActor2: 'Al Pacino',
    },
    {
      _id: 3,
      foreignTitle: 'The Godfather: Part II',
      hungarianTitle: 'A keresztapa 2',
      director: 'Francis Ford Coppola',
      releaseYear: 1974,
      length: 202,
      genre: 'crime, drama',
      imdbRank: '3',
      imdbAverage: 9.0,
      imdbID: 'tt0071562',
      mainActor1: 'Al Pacino',
      mainActor2: 'Robert De Niro',
    },
    {
      _id: 4,
      foreignTitle: 'Pulp Fiction',
      hungarianTitle: 'Ponyvaregény',
      director: 'Quentin Tarantino',
      releaseYear: 1994,
      length: 154,
      genre: 'crime, drama',
      imdbRank: '4',
      imdbAverage: 8.9,
      imdbID: 'tt0110912',
      mainActor1: 'John Travolta',
      mainActor2: 'Samuel L. Jackson',
    },
    {
      _id: 5,
      foreignTitle: 'The Good, the Bad and the Ugly',
      hungarianTitle: 'A jó, a rossz és a csúf',
      director: 'Sergio Leone',
      releaseYear: 1966,
      length: 161,
      genre: 'adventure, western',
      imdbRank: '5',
      imdbAverage: 8.8,
      imdbID: 'tt0060196',
      mainActor1: 'Clint Eastwood',
      mainActor2: 'Eli Wallach',
    },
    {
      _id: 6,
      foreignTitle: 'The Dark Knight',
      hungarianTitle: 'A sötét lovag',
      director: 'Christopher Nolan',
      releaseYear: 2008,
      length: 152,
      genre: 'action, crime, drama',
      imdbRank: '6',
      imdbAverage: 9.0,
      imdbID: 'tt0468569',
      mainActor1: 'Cristian Bale',
      mainActor2: 'Heath Leadger',
    },
    {
      _id: 7,
      foreignTitle: '12 Angry Men',
      hungarianTitle: '12 dühös ember',
      director: 'Sidney Lumet',
      releaseYear: 1957,
      length: 96,
      genre: 'crime, drama',
      imdbRank: '7',
      imdbAverage: 9.0,
      imdbID: 'tt0050083',
      mainActor1: 'Henry Fonda',
      mainActor2: 'Lee J. Cobb',
    },
    {
      _id: 8,
      foreignTitle: "Schindler's List",
      hungarianTitle: 'Schindler listája',
      director: 'Steven Spielberg',
      releaseYear: 1993,
      length: 195,
      genre: 'biography, drama, history',
      imdbRank: '8',
      imdbAverage: 9.0,
      imdbID: 'tt0108052',
      mainActor1: 'Liam Neeson',
      mainActor2: 'Ralph Fiennes',
    },
    {
      _id: 9,
      foreignTitle: 'The Lord of the Rings: The Return of the King',
      hungarianTitle: 'A Gyűrűk ura: A király visszatér',
      director: 'Peter Jackson',
      releaseYear: 2003,
      length: 201,
      genre: 'action, drama, adventure, fantasy',
      imdbRank: '9',
      imdbAverage: 9.0,
      imdbID: 'tt0167260',
      mainActor1: 'Elijah Wood',
      mainActor2: 'Viggo Mortensen',
    },
    {
      _id: 10,
      foreignTitle: 'Fight Club',
      hungarianTitle: 'Harcosok klubja',
      director: 'David Fincher',
      releaseYear: 1999,
      length: 139,
      genre: 'drama',
      imdbRank: '10',
      imdbAverage: 8.8,
      imdbID: 'tt0137523',
      mainActor1: 'Brad Pitt',
      mainActor2: 'Edward Norton',
    },
    {
      _id: 11,
      foreignTitle: 'Star Wars: Episode V - The Empire Strikes Back',
      hungarianTitle: 'A Birodalom visszavág',
      director: 'Irvin Kershner',
      releaseYear: 1980,
      length: 124,
      genre: 'action, adventure, fantasy, sci-fi',
      imdbRank: '11',
      imdbAverage: 8.7,
      imdbID: 'tt0080684',
      mainActor1: 'Mark Hamill',
      mainActor2: 'Harisson Ford',
    },
    {
      _id: 12,
      foreignTitle: 'The Lord of the Rings: The Fellowship of the Ring',
      hungarianTitle: 'Gyűrűk Ura: A gyűrű szövetsége',
      director: 'Peter Jackson',
      releaseYear: 2001,
      length: 178,
      genre: 'action, drama, adventure, fantasy',
      imdbRank: '12',
      imdbAverage: 8.8,
      imdbID: 'tt0120737',
      mainActor1: 'Elijah Wood',
      mainActor2: 'Ian McKellen',
    },
    {
      _id: 13,
      foreignTitle: "One Flew Over the Cuckoo's Nest",
      hungarianTitle: 'Száll a kakukk fészkére',
      director: 'Milos Forman',
      releaseYear: 1975,
      length: 130,
      genre: 'drama',
      imdbRank: '13',
      imdbAverage: 8.7,
      imdbID: 'tt0073486',
      mainActor1: 'Jack Nicholson',
      mainActor2: 'Louise Fletcher',
    },
    {
      _id: 14,
      foreignTitle: 'Inception',
      hungarianTitle: 'Eredet',
      director: 'Cristopher Nolen',
      releaseYear: 2010,
      length: 148,
      genre: 'action, adventure, sci-fi, thriller',
      imdbRank: '14',
      imdbAverage: 8.8,
      imdbID: 'tt1375666',
      mainActor1: 'Leonardo DiCaprio',
      mainActor2: 'Joseph Gordon-Levitt',
    },
    {
      _id: 15,
      foreignTitle: 'Goodfellas',
      hungarianTitle: 'Nagymenők',
      director: 'Martin Scorsese',
      releaseYear: 1990,
      length: 145,
      genre: 'biography, crime, drama',
      imdbRank: '15',
      imdbAverage: 8.7,
      imdbID: 'tt0099685',
      mainActor1: 'Robert DeNiro',
      mainActor2: 'Ray Liotta',
    },
    {
      _id: 16,
      foreignTitle: 'Star Wars',
      hungarianTitle: 'Csillagok háborúja',
      director: 'George Lucas',
      releaseYear: 1977,
      length: 121,
      genre: 'action, adventure, fantasy, sci-fi',
      imdbRank: '16',
      imdbAverage: 8.6,
      imdbID: 'tt0076759',
      mainActor1: 'Mark Hamill',
      mainActor2: 'Harisson Ford',
    },
    {
      _id: 17,
      foreignTitle: 'Seven Samurai',
      hungarianTitle: 'A hét szamuráj',
      director: 'Akira Kurosawa',
      releaseYear: 1954,
      length: 207,
      genre: 'action, drama',
      imdbRank: '17',
      imdbAverage: 8.6,
      imdbID: 'tt0047478',
      mainActor1: 'Toshiró Mifune',
      mainActor2: 'Takashi Shimura',
    },
    {
      _id: 18,
      foreignTitle: 'Forrest Gump',
      hungarianTitle: 'Forrest Gump',
      director: 'Robert Zemeckis',
      releaseYear: 1994,
      length: 142,
      genre: 'drama, romance',
      imdbRank: '18',
      imdbAverage: 8.8,
      imdbID: 'tt0109830',
      mainActor1: 'Tom Hanks',
      mainActor2: 'Robin Wright',
    },
    {
      _id: 19,
      foreignTitle: 'The Matrix',
      hungarianTitle: 'Mátrix',
      director: 'Lana Wachowski, Lilly Wachwoski',
      releaseYear: 1999,
      length: 136,
      genre: 'action, sci-fi',
      imdbRank: '19',
      imdbAverage: 8.7,
      imdbID: 'tt0133093',
      mainActor1: 'Keanu Reeves',
      mainActor2: 'Laurence Fishburne',
    },
    {
      _id: 20,
      foreignTitle: 'The Lord of the Rings: The Two Towers',
      hungarianTitle: 'A Gyűrűk Ura: A két torony',
      director: 'Peter Jackson',
      releaseYear: 2002,
      length: 179,
      genre: 'action, drama, adventure, fantasy',
      imdbRank: '20',
      imdbAverage: 8.8,
      imdbID: 'tt0167261',
      mainActor1: 'Elijah Wood',
      mainActor2: 'Ian McKellen',
    },
    {
      _id: 21,
      foreignTitle: 'Cidade de Deus/City of God',
      hungarianTitle: 'Isten városa',
      director: 'Fernando Meirelles, Kátia Lund',
      releaseYear: 2002,
      length: 113,
      genre: 'crime, drama',
      imdbRank: '21',
      imdbAverage: 8.6,
      imdbID: 'tt0317248',
      mainActor1: 'Alexandre Rodrigues',
      mainActor2: 'Leandro Firmino',
    },
    {
      _id: 22,
      foreignTitle: 'Se7en',
      hungarianTitle: 'Hetedik',
      director: 'David Fincher',
      releaseYear: 1995,
      length: 127,
      genre: 'crime, drama, mystery',
      imdbRank: '22',
      imdbAverage: 8.6,
      imdbID: 'tt0114369',
      mainActor1: 'Morgan Freeman',
      mainActor2: 'Brad Pitt',
    },
    {
      _id: 23,
      foreignTitle: 'The Silence of the Lambs',
      hungarianTitle: 'A bárányok hallgatnak',
      director: 'Jonathan Demme',
      releaseYear: 1991,
      length: 118,
      genre: 'crime, drama, thriller',
      imdbRank: '23',
      imdbAverage: 8.6,
      imdbID: 'tt0102926',
      mainActor1: 'Jodie Foster',
      mainActor2: 'Anthony Hopkins',
    },
    {
      _id: 24,
      foreignTitle: " C'era una volta il West / Once Upon a Time in the West",
      hungarianTitle: 'Volt egyszer egy vadnyugat',
      director: 'Sergio Leone',
      releaseYear: 1968,
      length: 165,
      genre: 'western',
      imdbRank: '24',
      imdbAverage: 8.5,
      imdbID: 'tt0064116',
      mainActor1: 'Henry Fonda',
      mainActor2: 'Charles Bronson',
    },
    {
      _id: 25,
      foreignTitle: 'Casablanca',
      hungarianTitle: 'Casablanca',
      director: 'Michael Curtiz',
      releaseYear: 1942,
      length: 102,
      genre: 'drama, romance, war',
      imdbRank: '25',
      imdbAverage: 8.5,
      imdbID: 'tt0034583',
      mainActor1: 'Humphrey Bogart',
      mainActor2: 'Ingrid Bergman',
    },
    {
      _id: 26,
      foreignTitle: 'The Usual Suspects',
      hungarianTitle: 'Közönséges bűnözők',
      director: 'Bryan Singer',
      releaseYear: 1995,
      length: 106,
      genre: 'crime, drama, mystery',
      imdbRank: '26',
      imdbAverage: 8.5,
      imdbID: 'tt0114814',
      mainActor1: 'Kevin Spacey',
      mainActor2: 'Gabriel Byrne',
    },
    {
      _id: 27,
      foreignTitle: 'Raiders of the Lost Ark',
      hungarianTitle: 'Az elveszett frigyláda fosztogatói',
      director: 'Steven Spielberg',
      releaseYear: 1981,
      length: 115,
      genre: 'action, adventure',
      imdbRank: '27',
      imdbAverage: 8.4,
      imdbID: 'tt0082971',
      mainActor1: 'Harrison Ford',
      mainActor2: 'Karen Allen',
    },
    {
      _id: 28,
      foreignTitle: 'Rear Window',
      hungarianTitle: 'Hátsó ablak',
      director: 'Alfred Hitchcock',
      releaseYear: 1954,
      length: 112,
      genre: 'mystery, thriller',
      imdbRank: '28',
      imdbAverage: 8.5,
      imdbID: 'tt0047396',
      mainActor1: 'James Stewart',
      mainActor2: 'Grace Kelly',
    },
    {
      _id: 29,
      foreignTitle: "It's a Wonderful Life",
      hungarianTitle: 'Az élet csodaszép',
      director: 'Frank Capra',
      releaseYear: 1946,
      length: 130,
      genre: 'drama, family, fantasy',
      imdbRank: '29',
      imdbAverage: 8.6,
      imdbID: 'tt0038650',
      mainActor1: 'James Stewart',
      mainActor2: 'Donna Reed',
    },
    {
      _id: 30,
      foreignTitle: 'Psycho',
      hungarianTitle: 'Psycho',
      director: 'Alfred Hitchcock',
      releaseYear: 1960,
      length: 109,
      genre: 'horror, mystery, thriller',
      imdbRank: '30',
      imdbAverage: 8.5,
      imdbID: 'tt0054215',
      mainActor1: 'Anthony Perkins',
      mainActor2: 'Janet Leigh',
    },
    {
      _id: 31,
      foreignTitle: 'Léon / Léon: The Professional',
      hungarianTitle: 'Léon, a profi',
      director: 'Luc Besson',
      releaseYear: 1994,
      length: 110,
      genre: 'action, crime, drama',
      imdbRank: '31',
      imdbAverage: 8.5,
      imdbID: 'tt0110413',
      mainActor1: 'Jean Reno',
      mainActor2: 'Gary Oldman',
    },
    {
      _id: 32,
      foreignTitle: 'Sunset Blvd.',
      hungarianTitle: 'Alkony sugárút',
      director: 'Billy Wilder',
      releaseYear: 1950,
      length: 110,
      genre: 'drama, film-noir',
      imdbRank: '32',
      imdbAverage: 8.4,
      imdbID: 'tt0043014',
      mainActor1: 'William Holden',
      mainActor2: 'Gloria Swanson',
    },
    {
      _id: 33,
      foreignTitle: 'American History X',
      hungarianTitle: 'Amerikai história X',
      director: 'Tony Kaye',
      releaseYear: 1998,
      length: 119,
      genre: 'crime, drama',
      imdbRank: '33',
      imdbAverage: 8.5,
      imdbID: 'tt0120586',
      mainActor1: 'Edward Norton',
      mainActor2: 'Edward Furlong',
    },
    {
      _id: 34,
      foreignTitle: 'Apocalypse Now',
      hungarianTitle: 'Apokalipszis most',
      director: 'Francis Ford Coppola',
      releaseYear: 1979,
      length: 147,
      genre: 'drama, mystery, war',
      imdbRank: '34',
      imdbAverage: 8.5,
      imdbID: 'tt0078788',
      mainActor1: 'Martin Sheen',
      mainActor2: 'Marlon Brando',
    },
    {
      _id: 35,
      foreignTitle: 'Terminator 2: Judgment Day',
      hungarianTitle: 'Terminátor 2. - Az ítélet napja',
      director: 'James Cameron',
      releaseYear: 1991,
      length: 137,
      genre: 'action, sci-fi',
      imdbRank: '35',
      imdbAverage: 8.6,
      imdbID: 'tt0103064',
      mainActor1: 'Arnold Schwarzenegger',
      mainActor2: 'Linda Hamilton',
    },
    {
      _id: 36,
      foreignTitle: 'Saving Private Ryan',
      hungarianTitle: 'Ryan közlegény megmentése',
      director: 'Steven Spielberg',
      releaseYear: 1998,
      length: 169,
      genre: 'drama, war',
      imdbRank: '36',
      imdbAverage: 8.6,
      imdbID: 'tt0120815',
      mainActor1: 'Tom Hanks',
      mainActor2: 'Matt Damon',
    },
    {
      _id: 37,
      foreignTitle: 'Memento',
      hungarianTitle: 'Mementó',
      director: 'Christopher Nolan',
      releaseYear: 2000,
      length: 113,
      genre: 'mystery, thriller',
      imdbRank: '37',
      imdbAverage: 8.4,
      imdbID: 'tt0209144',
      mainActor1: 'Guy Pearce',
      mainActor2: 'Carrie-Anne Moss',
    },
    {
      _id: 38,
      foreignTitle: 'City Lights',
      hungarianTitle: 'Nagyvárosi fények',
      director: 'Charles Chaplin',
      releaseYear: 1931,
      length: 87,
      genre: 'comedy, drama, romance',
      imdbRank: '38',
      imdbAverage: 8.5,
      imdbID: 'tt0021749',
      mainActor1: 'Charles Chaplin',
      mainActor2: 'Virginia Cherrill',
    },
    {
      _id: 39,
      foreignTitle:
        'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
      hungarianTitle:
        'Dr. Strangelove, avagy rájöttem, hogy nem kell félni a bombától, meg is lehet szeretni',
      director: 'Stanley Kubrick',
      releaseYear: 1964,
      length: 85,
      genre: 'comedy, war',
      imdbRank: '39',
      imdbAverage: 8.4,
      imdbID: 'tt0057012',
      mainActor1: 'Peter Sellers',
      mainActor2: 'George C. Scott',
    },
    {
      _id: 40,
      foreignTitle: 'Alien',
      hungarianTitle: 'A nyolcadik utas: a Halál',
      director: 'Ridley Scott',
      releaseYear: 1979,
      length: 117,
      genre: 'horror, sci-fi',
      imdbRank: '40',
      imdbAverage: 8.5,
      imdbID: 'tt0078748',
      mainActor1: 'Sigourney Weaver',
      mainActor2: 'Tom Skerritt',
    },
    {
      _id: 41,
      foreignTitle: 'Modern Times',
      hungarianTitle: 'Modern idők',
      director: 'Charles Chaplin',
      releaseYear: 1936,
      length: 97,
      genre: 'comedy, drama, romance',
      imdbRank: '41',
      imdbAverage: 8.5,
      imdbID: 'tt0027977',
      mainActor1: 'Charles Chaplin',
      mainActor2: 'Paulette Goddard',
    },
    {
      _id: 42,
      foreignTitle: 'Sen to Chihiro no kamikakushi / Spirited Away',
      hungarianTitle: 'Chihiro szellemországban',
      director: 'Hayao Miyazaki',
      releaseYear: 2001,
      length: 125,
      genre: 'animation, adventure, family',
      imdbRank: '42',
      imdbAverage: 8.6,
      imdbID: 'tt0245429',
      mainActor1: 'Daveigh Chase (English version)',
      mainActor2: 'Suzanne Pleshette (English version)',
    },
    {
      _id: 43,
      foreignTitle: 'North by Northwest',
      hungarianTitle: 'Észak-északnyugat',
      director: 'Alfred Hitchcock',
      releaseYear: 1959,
      length: 136,
      genre: 'action, adventure, mystery',
      imdbRank: '43',
      imdbAverage: 8.3,
      imdbID: 'tt0053125',
      mainActor1: 'Cary Grant',
      mainActor2: 'Eva Marie Saint',
    },
    {
      _id: 44,
      foreignTitle: 'Back to the Future',
      hungarianTitle: 'Vissza a jövőbe',
      director: 'Robert Zemeckis',
      releaseYear: 1985,
      length: 116,
      genre: 'adventure, comedy, sci-fi',
      imdbRank: '44',
      imdbAverage: 8.5,
      imdbID: 'tt0088763',
      mainActor1: 'Michael J. Fox',
      mainActor2: 'Christopher Lloyd',
    },
    {
      _id: 45,
      foreignTitle: 'La vita è bella / Life Is Beautiful',
      hungarianTitle: 'Az élet szép',
      director: 'Roberto Benigni',
      releaseYear: 1997,
      length: 116,
      genre: 'comedy, drama, romance',
      imdbRank: '45',
      imdbAverage: 8.6,
      imdbID: 'tt0118799',
      mainActor1: 'Roberto Benigni',
      mainActor2: 'Nicoletta Braschi',
    },
    {
      _id: 46,
      foreignTitle: 'The Shining',
      hungarianTitle: 'Ragyogás',
      director: 'Stanley Kubrick',
      releaseYear: 1980,
      length: 146,
      genre: 'drama, horror',
      imdbRank: '46',
      imdbAverage: 8.4,
      imdbID: 'tt0081505',
      mainActor1: 'Jack Nicholson',
      mainActor2: 'Shelley Duvall',
    },
    {
      _id: 47,
      foreignTitle: 'The Pianist',
      hungarianTitle: 'A zongorista',
      director: 'Roman Polanski',
      releaseYear: 2002,
      length: 150,
      genre: 'biography, drama, music',
      imdbRank: '47',
      imdbAverage: 8.5,
      imdbID: 'tt0253474',
      mainActor1: 'Adrien Brody',
      mainActor2: 'Thomas Kretschmann',
    },
    {
      _id: 48,
      foreignTitle: 'Citizen Kane',
      hungarianTitle: 'Aranypolgár',
      director: 'Orson Welles',
      releaseYear: 1941,
      length: 119,
      genre: 'drama, mystery',
      imdbRank: '48',
      imdbAverage: 8.3,
      imdbID: 'tt0033467',
      mainActor1: 'Orson Welles',
      mainActor2: 'Joseph Cotten',
    },
    {
      _id: 49,
      foreignTitle: 'The Departed',
      hungarianTitle: 'A tégla',
      director: 'Martin Scorsese',
      releaseYear: 2006,
      length: 151,
      genre: 'crime, drama, thriller',
      imdbRank: '49',
      imdbAverage: 8.5,
      imdbID: 'tt0407887',
      mainActor1: 'Leonardo DiCaprio',
      mainActor2: 'Matt Damon',
    },
    {
      _id: 50,
      foreignTitle: 'M - Eine Stadt sucht einen Mörder',
      hungarianTitle: 'M - Egy város keresi a gyilkost',
      director: 'Fritz Lang',
      releaseYear: 1931,
      length: 117,
      genre: 'crime, mystery, thriller',
      imdbRank: '50',
      imdbAverage: 8.3,
      imdbID: 'tt0022100',
      mainActor1: 'Peter Lorre',
      mainActor2: 'Ellen Widmann',
    },
    {
      _id: 51,
      foreignTitle: 'Paths of Glory',
      hungarianTitle: 'A dicsőség ösvényei',
      director: 'Stanley Kubrick',
      releaseYear: 1957,
      length: 88,
      genre: 'drama, war',
      imdbRank: '51',
      imdbAverage: 8.4,
      imdbID: 'tt0050825',
      mainActor1: 'Kirk Douglas',
      mainActor2: 'Ralph Meeker',
    },
    {
      _id: 52,
      foreignTitle: 'Vertigo',
      hungarianTitle: 'Szédülés',
      director: 'Alfred Hitchcock',
      releaseYear: 1958,
      length: 128,
      genre: 'mystery, romance, thriller',
      imdbRank: '52',
      imdbAverage: 8.3,
      imdbID: 'tt0052357',
      mainActor1: 'James Stewart',
      mainActor2: 'Kim Novak',
    },
    {
      _id: 53,
      foreignTitle: 'Django Unchained',
      hungarianTitle: 'Django elszabadul',
      director: 'Quentin Tarantino',
      releaseYear: 2012,
      length: 165,
      genre: 'drama, western',
      imdbRank: '53',
      imdbAverage: 8.4,
      imdbID: 'tt1853728',
      mainActor1: 'Jamie Foxx',
      mainActor2: 'Christoph Waltz',
    },
    {
      _id: 54,
      foreignTitle: 'Double Indemnity',
      hungarianTitle: 'Gyilkos vagyok',
      director: 'Billy Wilder',
      releaseYear: 1944,
      length: 107,
      genre: 'crime, drama, film-noir',
      imdbRank: '54',
      imdbAverage: 8.3,
      imdbID: 'tt0036775',
      mainActor1: 'Fred MacMurray',
      mainActor2: 'Barbara Stanwyck',
    },
    {
      _id: 55,
      foreignTitle: 'The Dark Knight Rises',
      hungarianTitle: 'A sötét lovag: Felemelkedés',
      director: 'Christopher Nolan',
      releaseYear: 2012,
      length: 164,
      genre: 'action, crime, drama',
      imdbRank: '55',
      imdbAverage: 8.4,
      imdbID: 'tt1345836',
      mainActor1: 'Chistian Bale',
      mainActor2: 'Tom Hardy',
    },
    {
      _id: 56,
      foreignTitle: 'Aliens',
      hungarianTitle: 'A bolygó neve: Halál',
      director: 'James Cameron',
      releaseYear: 1986,
      length: 137,
      genre: 'action, adventure, sci-fi',
      imdbRank: '56',
      imdbAverage: 8.4,
      imdbID: 'tt0090605',
      mainActor1: 'Sigourney Weaver',
      mainActor2: 'Michael Biehn',
    },
    {
      _id: 57,
      foreignTitle: 'Taxi Driver',
      hungarianTitle: 'Taxisofőr',
      director: 'Martin Scorsese',
      releaseYear: 1976,
      length: 114,
      genre: 'crime, drama',
      imdbRank: '57',
      imdbAverage: 8.2,
      imdbID: 'tt0075314',
      mainActor1: 'Robert DeNiro',
      mainActor2: 'Jodie Foster',
    },
    {
      _id: 58,
      foreignTitle: 'American Beauty',
      hungarianTitle: 'Amerikai szépség',
      director: 'Sam Mendes',
      releaseYear: 1999,
      length: 122,
      genre: 'drama',
      imdbRank: '58',
      imdbAverage: 8.4,
      imdbID: 'tt0169547',
      mainActor1: 'Kevin Spacey',
      mainActor2: 'Anette Bening',
    },
    {
      _id: 59,
      foreignTitle: 'The Green Mile',
      hungarianTitle: 'Halálsoron',
      director: 'Frank Darabont',
      releaseYear: 1999,
      length: 189,
      genre: 'crime, drama, fantasy',
      imdbRank: '59',
      imdbAverage: 8.6,
      imdbID: 'tt0120689',
      mainActor1: 'Tom Hanks',
      mainActor2: 'Michael Clarke Duncan',
    },
    {
      _id: 60,
      foreignTitle: 'Gladiator',
      hungarianTitle: 'Gladiátor',
      director: 'Ridley Scott',
      releaseYear: 2000,
      length: 155,
      genre: 'action, adventure, drama',
      imdbRank: '60',
      imdbAverage: 8.5,
      imdbID: 'tt0172495',
      mainActor1: 'Russell Crowe',
      mainActor2: 'Joaquin Phoenix',
    },
    {
      _id: 61,
      foreignTitle: 'The Intouchables',
      hungarianTitle: 'Életrevalók',
      director: 'Olivier Nakache, Éric Toledano',
      releaseYear: 2011,
      length: 112,
      genre: 'biography, comedy, drama',
      imdbRank: '61',
      imdbAverage: 8.5,
      imdbID: 'tt1675434',
      mainActor1: 'François Cluzet',
      mainActor2: 'Omar Sy',
    },
    {
      _id: 62,
      foreignTitle: 'WALL·E',
      hungarianTitle: 'WALL·E',
      director: 'Andrew Stanton',
      releaseYear: 2008,
      length: 88,
      genre: 'animation, adventure, family',
      imdbRank: '62',
      imdbAverage: 8.4,
      imdbID: 'tt0910970',
      mainActor1: 'Ben Burtt',
      mainActor2: 'Elissa Knight',
    },
    {
      _id: 63,
      foreignTitle: 'Das Leben der Anderen / The Lives of Others',
      hungarianTitle: 'A mások élete',
      director: 'Florian Henckel von Donnersmarck',
      releaseYear: 2006,
      length: 137,
      genre: 'drama, mystery, thriller',
      imdbRank: '63',
      imdbAverage: 8.4,
      imdbID: 'tt0405094',
      mainActor1: 'Ulrich Mühe',
      mainActor2: 'Martina Gedeck',
    },
    {
      _id: 64,
      foreignTitle: 'Toy Story 3',
      hungarianTitle: 'Toy Story 3',
      director: 'Lee Unkrich',
      releaseYear: 2010,
      length: 103,
      genre: 'animationn, adventure, comedy',
      imdbRank: '64',
      imdbAverage: 8.3,
      imdbID: 'tt0435761',
      mainActor1: 'Tom Hanks',
      mainActor2: 'Tim Allen',
    },
    {
      _id: 65,
      foreignTitle: 'The Great Dictator',
      hungarianTitle: 'A Diktátor',
      director: 'Charles Chaplin',
      releaseYear: 1940,
      length: 125,
      genre: 'comedy, drama, war',
      imdbRank: '65',
      imdbAverage: 8.4,
      imdbID: 'tt0032553',
      mainActor1: 'Charles Chaplin',
      mainActor2: 'Paulette Goddard',
    },
    {
      _id: 66,
      foreignTitle: 'The Prestige',
      hungarianTitle: 'A tökéletes trükk',
      director: 'Christopher Nolan',
      releaseYear: 2006,
      length: 130,
      genre: 'drama, mystery, thriller',
      imdbRank: '66',
      imdbAverage: 8.5,
      imdbID: 'tt0482571',
      mainActor1: 'Christian Bale',
      mainActor2: 'Hugh Jackman',
    },
    {
      _id: 67,
      foreignTitle: 'A Clockwork Orange',
      hungarianTitle: 'Mechanikus narancs',
      director: 'Stanley Kubrick',
      releaseYear: 1971,
      length: 136,
      genre: 'crime, sci-fi',
      imdbRank: '67',
      imdbAverage: 8.3,
      imdbID: 'tt0066921',
      mainActor1: 'Malcolm McDowell',
      mainActor2: 'Patrick Magee',
    },
    {
      _id: 68,
      foreignTitle: 'Lawrence of Arabia',
      hungarianTitle: 'Arábiai Lawrence',
      director: 'David Lean',
      releaseYear: 1962,
      length: 218,
      genre: 'adventure, biography, drama',
      imdbRank: '68',
      imdbAverage: 8.3,
      imdbID: 'tt0056172',
      mainActor1: "Peter O'Toole",
      mainActor2: 'Alec Guinness',
    },
    {
      _id: 69,
      foreignTitle: "Amélie / Le fabuleux destin d'Amélie Poulain",
      hungarianTitle: 'Amélie csodálatos élete',
      director: 'Jean-Pierre Jeunet',
      releaseYear: 2001,
      length: 122,
      genre: 'comedy, romance',
      imdbRank: '69',
      imdbAverage: 8.3,
      imdbID: 'tt0211915',
      mainActor1: 'Audrey Tautou',
      mainActor2: 'Mathieu Kassovitz',
    },
    {
      _id: 70,
      foreignTitle: 'To Kill a Mockingbird',
      hungarianTitle: 'Ne bántsátok a feketerigót!',
      director: 'Robert Mulligan',
      releaseYear: 1962,
      length: 129,
      genre: 'crime, drama',
      imdbRank: '70',
      imdbAverage: 8.3,
      imdbID: 'tt0056592',
      mainActor1: 'Gregory Peck',
      mainActor2: 'John Megna',
    },
    {
      _id: 71,
      foreignTitle: 'Reservoir Dogs',
      hungarianTitle: 'Kutyaszorítóban',
      director: 'Quentin Tarantino',
      releaseYear: 1992,
      length: 99,
      genre: 'crime, drama, thriller',
      imdbRank: '71',
      imdbAverage: 8.3,
      imdbID: 'tt0105236',
      mainActor1: 'Harvey Keitel',
      mainActor2: 'Tim Roth',
    },
    {
      _id: 72,
      foreignTitle: 'Das Boot',
      hungarianTitle: 'A tengeralattjáró',
      director: 'Wolfgang Petersen',
      releaseYear: 1981,
      length: 149,
      genre: 'drama, war',
      imdbRank: '72',
      imdbAverage: 8.4,
      imdbID: 'tt0082096',
      mainActor1: 'Jürgen Prochnow',
      mainActor2: 'Herbert Grönemeyer',
    },
    {
      _id: 73,
      foreignTitle: 'The Lion King',
      hungarianTitle: 'Az oroszlánkirály',
      director: 'Roger Allers, Rob Minkoff',
      releaseYear: 1994,
      length: 88,
      genre: 'animation, adventure, drama',
      imdbRank: '73',
      imdbAverage: 8.5,
      imdbID: 'tt0110357',
      mainActor1: 'Matthew Broderick',
      mainActor2: 'Jeremy Irons',
    },
    {
      _id: 74,
      foreignTitle: 'Nuovo Cinema Paradiso',
      hungarianTitle: 'Cinema Paradiso',
      director: 'Giuseppe Tornatore',
      releaseYear: 1988,
      length: 155,
      genre: 'drama, romance',
      imdbRank: '74',
      imdbAverage: 8.5,
      imdbID: 'tt0095765',
      mainActor1: 'Philippe Noiret',
      mainActor2: 'Enzo Cannavale',
    },
    {
      _id: 75,
      foreignTitle: 'Star Wars: Episode VI - Return of the Jedi',
      hungarianTitle: 'A Jedi visszatér',
      director: 'Richard Marquand',
      releaseYear: 1983,
      length: 131,
      genre: 'action, adventure, fantasy',
      imdbRank: '75',
      imdbAverage: 8.3,
      imdbID: 'tt0086190',
      mainActor1: 'Mark Hamill',
      mainActor2: 'Harrison Ford',
    },
    {
      _id: 76,
      foreignTitle: 'The Treasure of the Sierra Madre',
      hungarianTitle: 'A Sierra Madre kincse',
      director: 'John Huston',
      releaseYear: 1948,
      length: 126,
      genre: 'adventure, drama, western',
      imdbRank: '76',
      imdbAverage: 8.2,
      imdbID: 'tt0040897',
      mainActor1: 'Humphrey Bogart',
      mainActor2: 'Walter Huston',
    },
    {
      _id: 77,
      foreignTitle: 'The Third Man',
      hungarianTitle: 'A harmadik ember',
      director: 'Carol Reed',
      releaseYear: 1949,
      length: 104,
      genre: 'film-noir, mystery, thriller',
      imdbRank: '77',
      imdbAverage: 8.1,
      imdbID: 'tt0041959',
      mainActor1: 'Orson Welles',
      mainActor2: 'Joseph Cotten',
    },
    {
      _id: 78,
      foreignTitle: 'Once Upon a Time in America',
      hungarianTitle: 'Volt egyszer egy Amerika',
      director: 'Sergio Leone',
      releaseYear: 1984,
      length: 229,
      genre: 'crime, drama',
      imdbRank: '78',
      imdbAverage: 8.3,
      imdbID: 'tt0087843',
      mainActor1: 'Robert DeNiro',
      mainActor2: 'James Woods',
    },
    {
      _id: 79,
      foreignTitle: 'Requiem for a Dream',
      hungarianTitle: 'Rekviem egy álomért',
      director: 'Darren Aronofsky',
      releaseYear: 2000,
      length: 102,
      genre: 'drama',
      imdbRank: '79',
      imdbAverage: 8.3,
      imdbID: 'tt0180093',
      mainActor1: 'Ellen Burstyn',
      mainActor2: 'Jared Leto',
    },
    {
      _id: 80,
      foreignTitle: 'Eternal Sunshine of the Spotless Mind',
      hungarianTitle: 'Egy makulátlan elme örök ragyogása',
      director: 'Michel Gondry',
      releaseYear: 2004,
      length: 108,
      genre: 'drama, romance, sci-fi',
      imdbRank: '80',
      imdbAverage: 8.3,
      imdbID: 'tt0338013',
      mainActor1: 'Jim Carrey',
      mainActor2: 'Kate Winslet',
    },
    {
      _id: 81,
      foreignTitle: 'Full Metal Jacket',
      hungarianTitle: 'Acéllövedék',
      director: 'Stanley Kubrick',
      releaseYear: 1987,
      length: 116,
      genre: 'drama, war',
      imdbRank: '81',
      imdbAverage: 8.3,
      imdbID: 'tt0093058',
      mainActor1: 'Matthew Modine',
      mainActor2: 'R. Lee Ermey',
    },
    {
      _id: 82,
      foreignTitle: 'Oldeuboi',
      hungarianTitle: 'Oldboy',
      director: 'Park Chan-wook',
      releaseYear: 2003,
      length: 120,
      genre: 'action, drama, mystery',
      imdbRank: '82',
      imdbAverage: 8.4,
      imdbID: 'tt0364569',
      mainActor1: 'Choi Min-Sik',
      mainActor2: 'Yoo Ji-Tae',
    },
    {
      _id: 83,
      foreignTitle: 'Braveheart',
      hungarianTitle: 'A rettenthetetlen',
      director: 'Mel Gibson',
      releaseYear: 1995,
      length: 178,
      genre: 'biography, drama, history',
      imdbRank: '83',
      imdbAverage: 8.4,
      imdbID: 'tt0112573',
      mainActor1: 'Mel Gibson',
      mainActor2: 'Sophie Marceau',
    },
    {
      _id: 84,
      foreignTitle: 'L.A. Confidential',
      hungarianTitle: 'Szigorúan bizalmas',
      director: 'Curtis Hanson',
      releaseYear: 1997,
      length: 138,
      genre: 'crime, drama, mystery',
      imdbRank: '84',
      imdbAverage: 8.2,
      imdbID: 'tt0119488',
      mainActor1: 'Kevin Spacey',
      mainActor2: 'Russell Crowe',
    },
    {
      _id: 85,
      foreignTitle: 'Ladri di biciclette / Bicycle Thieves',
      hungarianTitle: 'Biciklitolvajok',
      director: 'Vittorio De Sica',
      releaseYear: 1948,
      length: 89,
      genre: 'drama',
      imdbRank: '85',
      imdbAverage: 8.3,
      imdbID: 'tt0040522',
      mainActor1: 'Lamberto Maggiorani',
      mainActor2: 'Enzo Staiola',
    },
    {
      _id: 86,
      foreignTitle: 'Chinatown',
      hungarianTitle: 'Kínai negyed',
      director: 'Roman Polanski',
      releaseYear: 1974,
      length: 130,
      genre: 'drama, mystery, thriller',
      imdbRank: '86',
      imdbAverage: 8.2,
      imdbID: 'tt0071315',
      mainActor1: 'Jack Nicholson',
      mainActor2: 'Faye Dunaway',
    },
    {
      _id: 87,
      foreignTitle: "Singin' in the Rain",
      hungarianTitle: 'Ének az esőben',
      director: 'Stanley Donen, Gene Kelly',
      releaseYear: 1952,
      length: 103,
      genre: 'comedy, musical, romance',
      imdbRank: '87',
      imdbAverage: 8.3,
      imdbID: 'tt0045152',
      mainActor1: 'Gene Kelly',
      mainActor2: "Donald O'Connor",
    },
    {
      _id: 88,
      foreignTitle: 'Mononoke-hime / Princess Mononoke',
      hungarianTitle: 'A vadon hercegnője',
      director: 'Hayao Miyazaki',
      releaseYear: 1997,
      length: 134,
      genre: 'animation, action, adventure',
      imdbRank: '88',
      imdbAverage: 8.4,
      imdbID: 'tt0119698',
      mainActor1: 'Yôji Matsuda',
      mainActor2: 'Yuriko Ishida',
    },
    {
      _id: 89,
      foreignTitle: 'Monty Python and the Holy Grail',
      hungarianTitle: 'Gyalog galopp',
      director: 'Terry Gilliam, Terry Jones',
      releaseYear: 1975,
      length: 91,
      genre: 'adventure, comedy, fantasy',
      imdbRank: '89',
      imdbAverage: 8.2,
      imdbID: 'tt0071853',
      mainActor1: 'Graham Chapman',
      mainActor2: 'John Cleese',
    },
    {
      _id: 90,
      foreignTitle: 'Metropolis',
      hungarianTitle: 'Metropolis',
      director: 'Fritz Lang',
      releaseYear: 1927,
      length: 153,
      genre: 'drama, sci-fi',
      imdbRank: '90',
      imdbAverage: 8.3,
      imdbID: 'tt0017136',
      mainActor1: 'Brigitte Helm',
      mainActor2: 'Alfred Abel',
    },
    {
      _id: 91,
      foreignTitle: 'Rashômon / Rashomon',
      hungarianTitle: 'A vihar kapujában',
      director: 'Akira Kurosawa',
      releaseYear: 1950,
      length: 88,
      genre: 'crime, drama, mystery',
      imdbRank: '91',
      imdbAverage: 8.2,
      imdbID: 'tt0042876',
      mainActor1: 'Toshirô Mifune',
      mainActor2: 'Machiko Kyô',
    },
    {
      _id: 92,
      foreignTitle: 'Some Like It Hot',
      hungarianTitle: 'Van, aki forrón szereti',
      director: 'Billy Wilder',
      releaseYear: 1959,
      length: 121,
      genre: 'comedy, music, romance',
      imdbRank: '92',
      imdbAverage: 8.2,
      imdbID: 'tt0053291',
      mainActor1: 'Marilyn Monroe',
      mainActor2: 'Tony Curtis',
    },
    {
      _id: 93,
      foreignTitle: 'Amadeus',
      hungarianTitle: 'Amadeus',
      director: 'Milos Forman',
      releaseYear: 1984,
      length: 160,
      genre: 'biography, drama, music',
      imdbRank: '93',
      imdbAverage: 8.4,
      imdbID: 'tt0086879',
      mainActor1: 'F. Murray Abraham',
      mainActor2: 'Tom Hulce',
    },
    {
      _id: 94,
      foreignTitle: '2001: A Space Odyssey',
      hungarianTitle: '2001: Űrodüsszeia',
      director: 'Stanley Kubrick',
      releaseYear: 1968,
      length: 159,
      genre: 'adventure, sci-fi',
      imdbRank: '94',
      imdbAverage: 8.3,
      imdbID: 'tt0062622',
      mainActor1: 'Keir Dullea',
      mainActor2: 'Gary Lockwood',
    },
    {
      _id: 95,
      foreignTitle: 'All About Eve',
      hungarianTitle: 'Mindent Éváról',
      director: 'Joseph L. Mankiewicz',
      releaseYear: 1950,
      length: 138,
      genre: 'drama',
      imdbRank: '95',
      imdbAverage: 8.2,
      imdbID: 'tt0042192',
      mainActor1: 'Bette Davis',
      mainActor2: 'Anne Baxter',
    },
    {
      _id: 96,
      foreignTitle: 'Witness for the Prosecution',
      hungarianTitle: 'A vád tanúja',
      director: 'Billy Wilder',
      releaseYear: 1957,
      length: 116,
      genre: 'crime, drama, mystery',
      imdbRank: '96',
      imdbAverage: 8.4,
      imdbID: 'tt0051201',
      mainActor1: 'Tyrone Power',
      mainActor2: 'Marlene Dietrich',
    },
    {
      _id: 97,
      foreignTitle: 'The Sting',
      hungarianTitle: 'A nagy balhé',
      director: 'George Roy Hill',
      releaseYear: 1973,
      length: 129,
      genre: 'comedy, crime, drama',
      imdbRank: '97',
      imdbAverage: 8.3,
      imdbID: 'tt0070735',
      mainActor1: 'Paul Newman',
      mainActor2: 'Robert Redford',
    },
    {
      _id: 98,
      foreignTitle: 'The Apartment',
      hungarianTitle: 'A legénylakás',
      director: 'Billy Wilder',
      releaseYear: 1960,
      length: 125,
      genre: 'comedy, drama, romance',
      imdbRank: '98',
      imdbAverage: 8.3,
      imdbID: 'tt0053604',
      mainActor1: 'Jack Lemmon',
      mainActor2: 'Shirley MacLaine',
    },
    {
      _id: 99,
      foreignTitle: 'Hotaru no haka / Grave of the Fireflies',
      hungarianTitle: 'Szentjánosbogarak sírja',
      director: 'Isao Takahata',
      releaseYear: 1988,
      length: 89,
      genre: 'animation, drama, war',
      imdbRank: '99',
      imdbAverage: 8.5,
      imdbID: 'tt0095327',
      mainActor1: 'Tsutomu Tatsumi',
      mainActor2: 'Ayano Shiraishi',
    },
    {
      _id: 100,
      foreignTitle: 'Indiana Jones and the Last Crusade',
      hungarianTitle: 'Indiana Jones és az utolsó kereszteslovag',
      director: 'Steven Spielberg',
      releaseYear: 1989,
      length: 127,
      genre: 'action, adventure',
      imdbRank: '100',
      imdbAverage: 8.2,
      imdbID: 'tt0097576',
      mainActor1: 'Harrison Ford',
      mainActor2: 'Sean Connery',
    },
  ];

  timestamps = [
    { timestampOfWatching: '2021-05-05T10:17:25Z' },
    { timestampOfWatching: '2020-08-05T16:44:18Z' },
    { timestampOfWatching: '2019-02-15T12:35:06Z' },
    { timestampOfWatching: '2020-03-11T00:23:07Z' },
    { timestampOfWatching: '2018-10-09T21:35:45Z' },
    { timestampOfWatching: '2020-12-26T12:19:54Z' },
    { timestampOfWatching: '2022-03-16T16:02:45Z' },
    { timestampOfWatching: '2021-11-19T23:31:59Z' },
    { timestampOfWatching: '2018-04-19T17:04:43Z' },
    { timestampOfWatching: '2018-04-26T23:14:25Z' },
    { timestampOfWatching: '2019-01-20T19:12:00Z' },
    { timestampOfWatching: '2019-05-18T14:24:17Z' },
    { timestampOfWatching: '2019-06-06T03:23:12Z' },
    { timestampOfWatching: '2019-10-15T12:18:57Z' },
    { timestampOfWatching: '2018-03-27T05:10:24Z' },
    { timestampOfWatching: '2019-06-10T22:36:31Z' },
    { timestampOfWatching: '2022-01-10T09:05:54Z' },
    { timestampOfWatching: '2020-11-23T05:05:24Z' },
    { timestampOfWatching: '2022-02-23T16:34:58Z' },
    { timestampOfWatching: '2022-01-18T11:26:33Z' },
    { timestampOfWatching: '2018-09-13T05:56:23Z' },
    { timestampOfWatching: '2022-02-19T19:28:30Z' },
    { timestampOfWatching: '2022-03-29T16:25:30Z' },
    { timestampOfWatching: '2021-07-16T02:23:56Z' },
    { timestampOfWatching: '2021-01-06T03:12:36Z' },
    { timestampOfWatching: '2019-01-05T06:35:58Z' },
    { timestampOfWatching: '2019-01-22T08:39:02Z' },
    { timestampOfWatching: '2018-07-24T02:06:09Z' },
    { timestampOfWatching: '2018-09-12T15:04:20Z' },
    { timestampOfWatching: '2020-12-06T10:10:57Z' },
    { timestampOfWatching: '2021-02-04T22:54:04Z' },
    { timestampOfWatching: '2021-01-12T05:28:35Z' },
    { timestampOfWatching: '2020-02-11T05:12:20Z' },
    { timestampOfWatching: '2021-05-05T20:57:24Z' },
    { timestampOfWatching: '2019-12-14T22:30:11Z' },
    { timestampOfWatching: '2018-12-02T17:45:19Z' },
    { timestampOfWatching: '2022-04-16T16:38:01Z' },
    { timestampOfWatching: '2022-03-09T04:28:38Z' },
    { timestampOfWatching: '2018-06-01T22:22:47Z' },
    { timestampOfWatching: '2020-11-17T08:49:48Z' },
    { timestampOfWatching: '2020-01-04T05:38:47Z' },
    { timestampOfWatching: '2018-11-18T05:18:11Z' },
    { timestampOfWatching: '2021-03-03T19:01:03Z' },
    { timestampOfWatching: '2019-05-16T17:41:27Z' },
    { timestampOfWatching: '2022-05-10T06:58:13Z' },
    { timestampOfWatching: '2021-01-27T14:46:28Z' },
    { timestampOfWatching: '2019-10-10T02:22:02Z' },
    { timestampOfWatching: '2020-10-10T11:54:46Z' },
    { timestampOfWatching: '2021-03-30T10:43:02Z' },
    { timestampOfWatching: '2022-03-14T12:49:07Z' },
    { timestampOfWatching: '2022-01-10T14:54:06Z' },
    { timestampOfWatching: '2019-12-25T19:42:16Z' },
    { timestampOfWatching: '2018-06-06T13:33:54Z' },
    { timestampOfWatching: '2021-02-11T21:04:03Z' },
    { timestampOfWatching: '2020-02-01T02:38:53Z' },
    { timestampOfWatching: '2021-10-19T03:31:40Z' },
    { timestampOfWatching: '2021-04-16T18:14:16Z' },
    { timestampOfWatching: '2020-03-08T11:58:46Z' },
    { timestampOfWatching: '2018-10-26T05:36:43Z' },
    { timestampOfWatching: '2020-02-29T07:12:08Z' },
    { timestampOfWatching: '2020-09-03T15:30:31Z' },
    { timestampOfWatching: '2020-10-07T23:32:37Z' },
    { timestampOfWatching: '2020-06-02T10:02:47Z' },
    { timestampOfWatching: '2018-04-20T14:15:55Z' },
    { timestampOfWatching: '2022-03-01T09:01:07Z' },
    { timestampOfWatching: '2022-01-26T16:10:03Z' },
    { timestampOfWatching: '2020-02-22T21:47:06Z' },
    { timestampOfWatching: '2020-01-24T23:34:51Z' },
    { timestampOfWatching: '2020-11-08T17:16:30Z' },
    { timestampOfWatching: '2022-05-27T07:33:39Z' },
    { timestampOfWatching: '2019-01-06T16:47:16Z' },
    { timestampOfWatching: '2019-07-22T18:01:58Z' },
    { timestampOfWatching: '2020-05-02T23:42:59Z' },
    { timestampOfWatching: '2018-11-29T06:14:17Z' },
    { timestampOfWatching: '2021-07-16T11:50:14Z' },
    { timestampOfWatching: '2021-05-14T12:29:16Z' },
    { timestampOfWatching: '2020-07-08T14:44:27Z' },
    { timestampOfWatching: '2019-04-11T23:35:30Z' },
    { timestampOfWatching: '2018-04-15T23:35:03Z' },
    { timestampOfWatching: '2020-08-04T04:57:56Z' },
    { timestampOfWatching: '2020-04-22T22:33:14Z' },
    { timestampOfWatching: '2019-08-08T02:04:29Z' },
    { timestampOfWatching: '2021-02-15T12:31:58Z' },
    { timestampOfWatching: '2019-07-22T05:42:56Z' },
    { timestampOfWatching: '2018-09-18T06:07:30Z' },
    { timestampOfWatching: '2019-01-29T03:41:53Z' },
    { timestampOfWatching: '2022-01-22T18:15:35Z' },
    { timestampOfWatching: '2021-11-03T01:51:21Z' },
    { timestampOfWatching: '2021-07-12T07:51:43Z' },
    { timestampOfWatching: '2018-08-20T10:34:29Z' },
    { timestampOfWatching: '2019-01-06T05:35:51Z' },
    { timestampOfWatching: '2021-01-28T23:01:50Z' },
    { timestampOfWatching: '2020-07-31T20:58:33Z' },
    { timestampOfWatching: '2020-02-07T18:35:06Z' },
    { timestampOfWatching: '2021-02-12T10:31:56Z' },
    { timestampOfWatching: '2019-07-08T23:43:50Z' },
    { timestampOfWatching: '2021-10-05T13:41:01Z' },
    { timestampOfWatching: '2021-11-07T04:30:02Z' },
    { timestampOfWatching: '2021-02-18T03:55:00Z' },
    { timestampOfWatching: '2021-04-08T13:36:44Z' },
  ];

  constructor() {}

  getAll(): Observable<WatchedMovie[]> {
    return of(this.list);
  }
}
